SELECT DISTINCT FELHASZNALO.ID,FELHASZNALO.NEV,PROFIL.PROFILKEP 
FROM ISMER,FELHASZNALO,KEPEK,PROFIL WHERE FELHASZNALO.ID IN 
(WITH A AS(SELECT * FROM ISMER2 WHERE KIID=1020), B AS (SELECT * FROM ISMER2 WHERE KIVELID=1020)
SELECT A.KIVELID FROM  A,B WHERE A.KIID=B.KIVELID AND B.KIID=A.KIVELID) AND FELHASZNALO.ID=PROFIL.SZEMELYID;

INSERT INTO ISMER2(KIID,KIVELID,IDO)VALUES(1020,1026,SYSTIMESTAMP);

DELETE FROM ISMER2 WHERE (KIVELID=670 AND KIID=672) OR (KIVELID=672 AND KIID=670);
