create or replace FUNCTION ADDIMAGE(V_ELERESIUT IN STRING,V_ALBUMNEV IN STRING,V_ID IN INT) RETURN INT IS 
 PRAGMA AUTONOMOUS_TRANSACTION;
 V_IDO TIMESTAMP;
 V_ALBUM ALBUM%ROWTYPE;
BEGIN 
  SELECT * INTO V_ALBUM FROM ALBUM  WHERE ALBUM.NEV=V_ALBUMNEV AND ALBUM.FELHASZNALOID=V_ID;
  INSERT INTO POSZT(FELADO,IDO,TARTALOM) VALUES(V_ID,SYSTIMESTAMP,'A felhasználó feltöltött egy képet a(z) '||V_ALBUMNEV||' albumba.'||V_ELERESIUT);
  INSERT INTO KEPEK(ALBUMNEV,ALBUMIDO,ELERESIUT,POSZTID) VALUES(V_ALBUM.NEV,V_ALBUM.IDO,V_ELERESIUT,POSZT_SEQ.CURRVAL);
  COMMIT;
  RETURN KEPEK_SEQ.CURRVAL;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
    V_IDO :=SYSTIMESTAMP;
    INSERT INTO ALBUM(FELHASZNALOID,NEV,IDO) VALUES(V_ID,V_ALBUMNEV,V_IDO);
    INSERT INTO POSZT(FELADO,IDO,TARTALOM) VALUES(V_ID,SYSTIMESTAMP,'A felhasználó feltöltött egy képet a(z) '||V_ALBUMNEV||' albumba.'||V_ELERESIUT);
    INSERT INTO KEPEK(ALBUMNEV,ALBUMIDO,ELERESIUT,POSZTID) VALUES(V_ALBUMNEV,V_IDO,V_ELERESIUT,POSZT_SEQ.CURRVAL);  
    COMMIT;
    RETURN KEPEK_SEQ.CURRVAL;
END;