create or replace PROCEDURE KLUBHOZZAAD(V_NEV IN STRING,V_TULAJDONOS IN INTEGER,V_KEZDET IN DATE,V_LEIRAS IN STRING) IS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO FELHASZNALO(NEV) VALUES(V_NEV);
  INSERT INTO KLUB(ID,TULAJDONOS,KEZDET,LEIRAS) VALUES(FELHASZNALO_SEQ.CURRVAL,V_TULAJDONOS,V_KEZDET,V_LEIRAS);
  INSERT INTO TAGJA(SZEMELYID,KLUBID) VALUES(V_TULAJDONOS,FELHASZNALO_SEQ.CURRVAL);
  COMMIT;
END;